### ISSUE TITLE
Scale the application

### ISSUE THREAD

**Issue by Lucki2g** [DevelOpsITU/MiniTwit#175]
Links etc. can be found in #174 
(@Thomsen96 - we need you for this, since we do not have permission to create droplets in digitalocean) 
- We assume this was because of the leaked API key and not permissions

Needs to be done:
- [x] Add a new application server to Vagrant File
- [x] Create script for creating Digital Ocean loadbalancer 
- [x] Run Vagrant file to create extra application server
- [x] Run init script to setup application server
- [x] Run the script to create loadbalancer  
- [x] Reassign  Floating IP from application server to loadbalancer (not possible)
- [x] Point Domain at load balancer

**Comment by Turboen** [comment]
**TODO:** Add tags to droplets on init ('application' for ApplicationServers... etc.)

**Comment by Lucki2g** [comment]
**TODO**: Make sure JQ is installed

**Comment by Turboen** [comment]
Working on branch feature/#175-scale-the-application **(IN SERVERDEPLOYMENT PROJECT)**
